name: 'Dependabot SHA Comment Action'
description: 'Update version comment for SHA pin of GitHub Actions on Dependabot update.'
author: timmeinerzhagen
inputs: 
  GITHUB_TOKEN:
    description: 'Github token of the repository with scopes repos and workflows'
    required: true
branding:
  icon: 'lock'  
  color: 'yellow'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ inputs.GITHUB_TOKEN }}

    - name: Check Pull Request Meta
      uses: actions/github-script@v5
      id: check
      with:
        script: |
          ## Check if correct event ##
          if (context.eventName !== 'pull_request_target') {
            core.setFailed("This action can only be used with the 'pull_request_target' trigger.");
          } else {
            ## Check if PR opened by Dependabot ##
            if (context.payload.sender.login == 'dependabot[bot]') {
              ## Check if Dependabot PR is for GitHub Actions ##
              if (context.payload.pull_request.labels.includes('github-actions') {
                core.info("Processing the Pull Request...")
                return true;
              } else {
                core.info("Not a GitHub Actions Dependabot Pull Request.");
              }
            } else {
              core.info("Not a Dependabot Pull Request.");
            }
          }

    - name: Get Pull Request Diff
      shell: bash
      id: diff
      if: steps.check.outputs.result
      run: |
        ## Prepare Branches ##
        git checkout $HEAD
        git branch --set-upstream-to=origin/$HEAD $HEAD
        git pull --all

        ## Get Diff; add to ENV ##
        DIFF=$(git diff origin/$BASE $HEAD | awk 1 ORS='\\n')
        echo 'DIFF<<EOF' >> $GITHUB_ENV
        echo $DIFF >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      env:
        BASE: ${{ github.event.pull_request.base.ref }}
        HEAD: ${{ github.event.pull_request.head.ref }}

    - name: Add Comment to Dependency SHA
      uses: actions/github-script@v5
      if: steps.check.outputs.result
      with:
        script: |
          ## Run js checking diff and adjusting version ##
          const script = require('./src/version-change.js')
          script({process, context, exec})

    - name: Push file changes
      shell: bash
      if: steps.check.outputs.result
      run: |
        git config --global user.name GitHub Actions
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Add Version Comment"
        git push 
